#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

if [ "$#" -lt 2 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE="$1"
server_ip="$2"

scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$PATH_TO_FILE" ubuntu@"$server_ip":~/